name: 'Cloudflare WARP Connector'
author: 'Farees <fareesdeveloper@outlook.com>'
description: 'Sets up Cloudflare WARP client using OAuth credentials'
inputs:
  organization:
    description: 'Organization Name'
    required: true
  cloudflare_access_client_id:
    description: 'Cloudflare Access Client ID'
    required: true
  cloudflare_client_secret:
    description: 'Cloudflare Client Secret'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: Fariz-fx/cloudflare-warp-connector
        ref: main
        path: cloudflare-warp-connector

    - name: Install Cloudflare WARP
      run: |
        curl -fsSL https://pkg.cloudflareclient.com/pubkey.gpg | sudo gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list
        sudo apt update && sudo apt install cloudflare-warp -y
      shell: bash

    - name: Register & Connect
      run: |
        warp-cli --accept-tos register \
          --auth-user "${{ inputs.cloudflare_access_client_id }}" \
          --auth-password "${{ inputs.cloudflare_client_secret }}" \
          --organization "${{ inputs.organization }}"
        warp-cli --accept-tos connect
        ./scripts/cf-warp-pre-connect.sh -m 10
      shell: bash
      working-directory: cloudflare-warp-connector

    - name: Validate Connection
      run: |
        warp-cli --accept-tos status
      shell: bash

branding:
  icon: 'cloud'
  color: 'orange'